class CreateMyEvas < ActiveRecord::Migration[5.2]
  def change
    create_table :my_evas do |t|
      t.integer "question_01"
      t.integer "question_02"
      t.integer "question_03"
      t.integer "question_04"
      t.integer "question_05"
      t.integer "question_06"
      t.integer "question_07"
      t.integer "question_08"
      t.integer "question_09"
      t.integer "question_10"
      t.integer "question_11"
      t.integer "question_12"
      t.integer "question_13"
      t.integer "question_14"
      t.integer "question_15"
      t.integer "question_16"
      t.integer "question_17"
      t.integer "question_18"
      t.integer "question_19"
      t.integer "question_20"
      t.integer "question_21"
      t.integer "question_22"
      t.integer "question_23"
      t.integer "question_24"
      t.integer "question_25"
      t.integer "question_26"
      t.integer "question_27"
      t.integer "question_28"
      t.integer "question_29"
      t.integer "question_30"
      t.integer "question_31"
      t.integer "question_32"
      t.integer "question_33"
      t.integer "question_34"
      t.integer "question_35"
      t.integer "question_36"
      t.integer "question_37"
      t.integer "question_38"
      t.integer "question_39"
      t.integer "question_40"
      t.integer "question_41"
      t.integer "question_42"
      t.integer "question_43"
      t.integer "question_44"
      t.integer "question_45"
      t.integer "question_46"
      t.integer "evaluated_user_id"
      t.timestamps
    end
  end
end
