class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @eva = MyEva.find_by(evaluated_user_id: current_user.id)
    @otheva = OthEva.find_by( evaluated_user_id: current_user.id )
    
    @otheva01 = OthEva.find_by( question_01: 1 , evaluated_user_id: current_user.id )
    @otheva02 = OthEva.find_by( question_02: 1 , evaluated_user_id: current_user.id )
    @otheva03 = OthEva.find_by( question_03: 1 , evaluated_user_id: current_user.id )
    @otheva04 = OthEva.find_by( question_04: 1 , evaluated_user_id: current_user.id )
    @otheva05 = OthEva.find_by( question_05: 1 , evaluated_user_id: current_user.id )
    @otheva06 = OthEva.find_by( question_06: 1 , evaluated_user_id: current_user.id )
    @otheva07 = OthEva.find_by( question_07: 1 , evaluated_user_id: current_user.id )
    @otheva08 = OthEva.find_by( question_08: 1 , evaluated_user_id: current_user.id )
    @otheva09 = OthEva.find_by( question_09: 1 , evaluated_user_id: current_user.id )
    @otheva10 = OthEva.find_by( question_10: 1 , evaluated_user_id: current_user.id )
    @otheva11 = OthEva.find_by( question_11: 1 , evaluated_user_id: current_user.id )
    @otheva12 = OthEva.find_by( question_12: 1 , evaluated_user_id: current_user.id )
    @otheva13 = OthEva.find_by( question_13: 1 , evaluated_user_id: current_user.id )
    @otheva14 = OthEva.find_by( question_14: 1 , evaluated_user_id: current_user.id )
    @otheva15 = OthEva.find_by( question_15: 1 , evaluated_user_id: current_user.id )
    @otheva16 = OthEva.find_by( question_16: 1 , evaluated_user_id: current_user.id )
    @otheva17 = OthEva.find_by( question_17: 1 , evaluated_user_id: current_user.id )
    @otheva18 = OthEva.find_by( question_18: 1 , evaluated_user_id: current_user.id )
    @otheva19 = OthEva.find_by( question_19: 1 , evaluated_user_id: current_user.id )
    @otheva20 = OthEva.find_by( question_20: 1 , evaluated_user_id: current_user.id )
    @otheva21 = OthEva.find_by( question_21: 1 , evaluated_user_id: current_user.id )
    @otheva22 = OthEva.find_by( question_22: 1 , evaluated_user_id: current_user.id )
    @otheva23 = OthEva.find_by( question_23: 1 , evaluated_user_id: current_user.id )
    @otheva24 = OthEva.find_by( question_24: 1 , evaluated_user_id: current_user.id )
    @otheva25 = OthEva.find_by( question_25: 1 , evaluated_user_id: current_user.id )
    @otheva26 = OthEva.find_by( question_26: 1 , evaluated_user_id: current_user.id )
    @otheva27 = OthEva.find_by( question_27: 1 , evaluated_user_id: current_user.id )
    @otheva28 = OthEva.find_by( question_28: 1 , evaluated_user_id: current_user.id )
    @otheva29 = OthEva.find_by( question_29: 1 , evaluated_user_id: current_user.id )
    @otheva30 = OthEva.find_by( question_30: 1 , evaluated_user_id: current_user.id )
    @otheva31 = OthEva.find_by( question_31: 1 , evaluated_user_id: current_user.id )
    @otheva32 = OthEva.find_by( question_32: 1 , evaluated_user_id: current_user.id )
    @otheva33 = OthEva.find_by( question_33: 1 , evaluated_user_id: current_user.id )
    @otheva34 = OthEva.find_by( question_34: 1 , evaluated_user_id: current_user.id )
    @otheva35 = OthEva.find_by( question_35: 1 , evaluated_user_id: current_user.id )
    @otheva36 = OthEva.find_by( question_36: 1 , evaluated_user_id: current_user.id )
    @otheva37 = OthEva.find_by( question_37: 1 , evaluated_user_id: current_user.id )
    @otheva38 = OthEva.find_by( question_38: 1 , evaluated_user_id: current_user.id )
    @otheva39 = OthEva.find_by( question_39: 1 , evaluated_user_id: current_user.id )
    @otheva40 = OthEva.find_by( question_40: 1 , evaluated_user_id: current_user.id )
    @otheva41 = OthEva.find_by( question_41: 1 , evaluated_user_id: current_user.id )
    @otheva42 = OthEva.find_by( question_42: 1 , evaluated_user_id: current_user.id )
    @otheva43 = OthEva.find_by( question_43: 1 , evaluated_user_id: current_user.id )
    @otheva44 = OthEva.find_by( question_44: 1 , evaluated_user_id: current_user.id )
    @otheva45 = OthEva.find_by( question_45: 1 , evaluated_user_id: current_user.id )
    @otheva46 = OthEva.find_by( question_46: 1 , evaluated_user_id: current_user.id )


  end
end
